vim.keymap.set("n", "<space><space>x", "<cmd>source %<CR>", { desc = "Source file" })
vim.keymap.set("v", "<space>x", ":lua<CR>", { desc = "Source selection" })
vim.keymap.set("n", "<M-j>", "<cmd>cnext<CR>", { desc = "Quickfix Next" })
vim.keymap.set("n", "<M-k>", "<cmd>cprev<CR>", { desc = "Quickfix Prev" })
vim.keymap.set('n', '[d', function() vim.diagnostic.goto_prev() end, { desc = "Diagnostic Prev" })
vim.keymap.set('n', ']d', function() vim.diagnostic.goto_next() end, { desc = "Diagnostic Next" })
vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", { desc = "Move line up" })
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", { desc = "Move line down" })
vim.keymap.set('n', 'J', "mzJ`z", { desc = "Better merge lines" })
vim.keymap.set('n', 'n', "nzzzv", { desc = "Better search next" })
vim.keymap.set('n', 'N', "Nzzzv", { desc = "Better search prev" })
