vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Hover" })
vim.keymap.set("n", "<space><space>x", "<cmd>source %<CR>", { desc = "Source file" })
vim.keymap.set("v", "<space>x", ":lua<CR>", { desc = "Source selection" })
vim.keymap.set("n", "[d", function()
  vim.diagnostic.goto_prev()
end, { desc = "Diagnostic Prev" })
vim.keymap.set("n", "]d", function()
  vim.diagnostic.goto_next()
end, { desc = "Diagnostic Next" })
vim.keymap.set("n", "J", "mzJ`z", { desc = "Better merge lines" })
vim.keymap.set("n", "n", "nzzzv", { desc = "Better search next" })
vim.keymap.set("n", "N", "Nzzzv", { desc = "Better search prev" })
vim.keymap.set("n", "q:", function() end, { desc = "Typo quit fix" })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Automatically quit highlight mode" })
vim.keymap.set("n", "tsi", "<cmd>TwoslashQueriesInspect<CR>", { desc = "Typescript inspect" })
vim.keymap.set("n", "<space>tih", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end, { desc = "Toggle Inlay Hints" })
