---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  -- test
  -- { import = "astrocommunity.test.neotest" },
  -- recipes
  { import = "astrocommunity.recipes.telescope-lsp-mappings" },
  -- workflow
  -- { import = "astrocommunity.workflow.hardtime-nvim" },
  -- colorschemes
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.colorscheme.dracula-nvim" },
  { import = "astrocommunity.colorscheme.bamboo-nvim" },
  { import = "astrocommunity.colorscheme.everforest" },
  { import = "astrocommunity.colorscheme.fluoromachine-nvim" },
  { import = "astrocommunity.colorscheme.github-nvim-theme" },
  { import = "astrocommunity.colorscheme.gruvbox-baby" },
  { import = "astrocommunity.colorscheme.gruvbox-nvim" },
  { import = "astrocommunity.colorscheme.helix-nvim" },
  { import = "astrocommunity.colorscheme.iceberg-vim" },
  { import = "astrocommunity.colorscheme.kanagawa-nvim" },
  { import = "astrocommunity.colorscheme.melange-nvim" },
  { import = "astrocommunity.colorscheme.mellow-nvim" },
  { import = "astrocommunity.colorscheme.mini-base16" },
  { import = "astrocommunity.colorscheme.monokai-pro-nvim" },
  -- { import = "astrocommunity.colorscheme.neosolarized-nvim" },
  { import = "astrocommunity.colorscheme.nightfox-nvim" },
  { import = "astrocommunity.colorscheme.nord-nvim" },
  { import = "astrocommunity.colorscheme.nordic-nvim" },
  { import = "astrocommunity.colorscheme.nvim-juliana" },
  { import = "astrocommunity.colorscheme.onedarkpro-nvim" },
  { import = "astrocommunity.colorscheme.oxocarbon-nvim" },
  { import = "astrocommunity.colorscheme.poimandres-nvim" },
  { import = "astrocommunity.colorscheme.rose-pine" },
  { import = "astrocommunity.colorscheme.sonokai" },
  { import = "astrocommunity.colorscheme.vscode-nvim" },
  { import = "astrocommunity.colorscheme.tokyonight-nvim" },
  -- lsp
  -- { import = "astrocommunity.lsp.ts-error-translator-nvim" },
  -- editing-support
  -- { import = "astrocommunity.editing-support.refactoring-nvim" },
  -- packs
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.pack.typescript-all-in-one" },
  -- { import = "astrocommunity.pack.terraform" },
  { import = "astrocommunity.pack.html-css" },
  -- { import = "astrocommunity.pack.markdown" },
  -- { import = "astrocommunity.pack.angular" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.toml" },
  -- { import = "astrocommunity.pack.java" },
  { import = "astrocommunity.pack.yaml" },
  -- { import = "astrocommunity.pack.fish" },
  -- { import = "astrocommunity.pack.helm" },
  -- { import = "astrocommunity.pack.sql" },
  -- { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.go" },
}
